In [1]:
import numpy as np

# Multidimesonal Array'ların elemanlarına ulaşmak.

In [3]:
a = np.arange(1,21).reshape([4,5])

In [4]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
a[0] #ilk satırını getirdi

array([1, 2, 3, 4, 5])

In [8]:
a[0][1] # birinci satır birinci eleman

2

In [10]:
a[0,0] #0. satır 0. eleman

1

In [11]:
a[0][0]

1

In [13]:
a.ndim

2

In [14]:
a[0].ndim

1

In [15]:
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
a[1][1] = 10

In [18]:
a #güncellendi.

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
a[1][1] = 10.27

In [20]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
# float da versek halihazırda array oluştuğundan arrayimizin default veri tipi halinde eklenir.

In [22]:
a[1][1] = "40"

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 40,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
a[1][1] = "30.1" #olmaz çünkü iki kere dönüştürmesi gerekir


ValueError: invalid literal for int() with base 10: '30.1'

In [27]:
a[1][1] = "a"

ValueError: invalid literal for int() with base 10: 'a'

### Slice indexing

In [28]:
a = np.arange(1,21).reshape(4,5)

In [30]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
a[1]

array([ 6,  7,  8,  9, 10])

In [34]:
a[0:3] # 0 ile 3 arasındakini getir 0 1 2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
a[::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [43]:
a[1:4:2] # atlama sayısı start stop step

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [44]:
# Bütün rowları al ama sadece 3. column u al

In [46]:
a[:,3] # dikey olan bir şeyi yataylaştırdı.

array([ 4,  9, 14, 19])

In [47]:
a[0,2:4]

array([3, 4])