In [1]:
import numpy as np

#  Splitting

In [2]:
l = [10, 20, 30, 40, 50, 60, 70, 80]

In [3]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [9]:
np.split(l, [2,6]) # aynı iekilde çalışır normal python ile sadewce böleceğimiz cism iilk yazıp böleceğimiz yerleri tupel veya list içöinbde veririrz.

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [10]:
np.split(l,[2,4])

[array([10, 20]), array([30, 40]), array([50, 60, 70, 80])]

In [11]:
#bu bölme bir array'de de yapılabilirdi.

In [13]:
l = np.array(l)

In [15]:
l

array([10, 20, 30, 40, 50, 60, 70, 80])

In [16]:
np.split(l , [4,6])

[array([10, 20, 30, 40]), array([50, 60]), array([70, 80])]

### Split sonucunu birden çok değişkene eşitleme

In [17]:
x, y, z = np.split(l, [2, 6])

In [18]:
print(x, y, z)

[10 20] [30 40 50 60] [70 80]


### Vsplit

In [23]:
a = np.arange(20).reshape(2,10)

In [24]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
np.vsplit(a, [1]) #vsplit vertical split demektir.

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [30]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Hsplit

In [31]:
a = np.arange(20).reshape(2,10)

In [32]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [34]:
np.hsplit(a, [3])

[array([[ 0,  1,  2],
        [10, 11, 12]]),
 array([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19]])]

In [35]:
np.hsplit(a, [4])

[array([[ 0,  1,  2,  3],
        [10, 11, 12, 13]]),
 array([[ 4,  5,  6,  7,  8,  9],
        [14, 15, 16, 17, 18, 19]])]

In [36]:
#dikey kesim bu da yazdığımız yere çzigi atıyoruz gibi düşün.

In [39]:
x, y = np.hsplit(a, [3])

In [40]:
print(x, y)

[[ 0  1  2]
 [10 11 12]] [[ 3  4  5  6  7  8  9]
 [13 14 15 16 17 18 19]]
