In [2]:
import numpy as np

#  ARDIŞIK SAYILARDAN ARRAY OLUŞTURMAK

In [3]:
# [0, 12)

In [5]:
np.arange(0,12) #12 dahil değil yani.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [10]:
np.arange(2,12,-2) # gidilemeyeceği için boş döndürdü.

array([], dtype=int32)

In [12]:
np.arange(12,2,-2) #ama burda olur.

array([12, 10,  8,  6,  4])