In [1]:
import numpy as np


#  Concetenation

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
b = np.array([5, 6, 7, 8])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b

array([5, 6, 7, 8])

In [9]:
# güncellenmez
np.concatenate([a,b]) # list içinde veriyor gibi vermeliyiz. Birleştirdi.

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
l = np.array([9, 10, 11])

In [11]:
np.concatenate([a, b, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
c = np.array([12, 13.1])

In [13]:
np.concatenate([a,b,l,c])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 11. ,
       12. , 13.1])

In [14]:
 # concatenate olanların içinden biri float ise hepsi float olur önceden konuşmuştuk.

In [15]:
# bir elemenaı string ise de hepsi string olur.

In [16]:
# aynı şekilde arrayler ile tuple ve listeler de aynı şekilde birleştirilebilr.

### Size mismatch

In [17]:
a

array([1, 2, 3, 4])

In [20]:
x = np.array([[1,2,3],
            [4,5,6]])

In [21]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
x.size

6

In [23]:
x.shape

(2, 3)

In [26]:
a.shape # Dimention 1'den fazla olursa row column mantığı gelir şimdilik bir sayı öbeğidir.

(4,)

In [27]:
a.size 

4

In [31]:
# SHAPE MİSMATCH HATASI
np.concatenate([a, x])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [32]:
np.concatenate([x, x]) # Fark ettiysek birleştirme dikeyde yani axis = 0'da oldu yatayda olamsını istersek belirtmeliyiz.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [33]:
# axis = 1 ile.

In [36]:
np.concatenate([x, x], axis = 1) #bakın sağa doğru birleştirdi.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])