In [1]:
import numpy as np

# Sum Methodu

In [2]:
#verilen conditionı kaç elemanın sağladığını bulalım.

In [3]:
a = np.arange(1,21).reshape(4,5)

In [4]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
np.sum(a) #bütün değerler toplandı.

210

In [7]:
filt = a < 5

In [8]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [9]:
np.sum(filt)

4

In [10]:
a[filt]

array([1, 2, 3, 4])

In [12]:
np.sum(a[filt]) # filtreye giren elemanları toplar.

10

In [13]:
a[filt]

array([1, 2, 3, 4])

In [14]:
filt = (a > 5) & (a < 9)

In [15]:
a[filt]

array([6, 7, 8])

In [16]:
sum(a[filt])

21

In [17]:
filt = ~(a > 5) & (a < 9)

In [18]:
a[filt]

array([1, 2, 3, 4, 5])

In [19]:
sum(a[filt])

15

### Belli bir axis üzerinde toplama

In [20]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
np.sum(a, axis = 0) #dikeyde topladı.

array([34, 38, 42, 46, 50])

In [22]:
np.sum(a, axis = 1) # yatayda topladı

array([15, 40, 65, 90])

In [25]:
np.sum(a, axis = 0).shape

(5,)