In [1]:
import numpy as np

# Subarray


In [7]:
a = np.arange(1,21).reshape(4,5)

In [8]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
b = a[:2, :3]

In [10]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [11]:
b.ndim

2

In [13]:
b[0][0] = 100

In [14]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [15]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [16]:
# ikisinde de değişmiş

In [18]:
#bu da aynı hafızayı kullandıklarının belritisidir.

In [19]:
# aynı list mantığı işler burada.

In [20]:
#bunu copy() mantığı ile çözebiliyoruz.

### Copy()

In [21]:
a = np.arange(1,21).reshape([4,5])

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
b = a[:2, :3].copy()

In [26]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [28]:
b[0][0] = 100

In [29]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [30]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
# bakın değişmedi.