In [1]:
import numpy as np

# ARALIĞI EŞİT UZAKLIKTAKİ NOKTALARA BÖLMEK

In [2]:
# Bir aralığın başlangıcını ve bitişini verip onu eşit şekilde bölmeyi göreceğiz.

In [3]:
# Default olarak 50 nokta döndürür.

In [5]:
np.linspace(1,2) # başlangıç ve btitş de dahildir.

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

## Kaç parçaya böelceğimizi bulmak

In [8]:
np.linspace(1,2,num = 3) # 1 ve 2 de dahil 3 nokta üret dedik


array([1. , 1.5, 2. ])

In [10]:
np.linspace(1,2,3) # aynı işi yapıyor.

array([1. , 1.5, 2. ])

In [14]:
np.linspace(1,2,3,endpoint = False) #endpoint bitiş noktasını 3 tane böldüğümüz sayıya dahil olup olmadığını sorar.

array([1.        , 1.33333333, 1.66666667])

In [16]:
np.linspace(1.5, 4.7, 3) # floatlar da olur.

array([1.5, 3.1, 4.7])