In [1]:
import numpy as np

# ARRAY İŞLEMLERİ

In [2]:
# * OPERATÖRÜ İKİ LİSTE ARASINDA İŞLEVSİZDİR HAT ADÖNDÜRÜR.

In [3]:
a = [1, 2, 3]
b = [2, 4, 8]

In [4]:
# bir skaler ile çarparsak ise concetenation yapar

In [5]:
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
# + operatörü de aynısını yapıyor.

In [7]:
# numpy ise eleman bazlı yapar.

In [8]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 8])

In [10]:
a * b # element wise yaparç

array([ 2,  8, 24])

In [11]:
a * b

array([ 2,  8, 24])

In [12]:
a * 2

array([2, 4, 6])

In [13]:
b * 2

array([ 4,  8, 16])

In [14]:
#element wise olduğundan eleman sayılaerının eşit olması lazım.

In [16]:
a + 2 # tüm elemanlarını 2 ile ytoplar

array([3, 4, 5])

In [17]:
a + b

array([ 3,  6, 11])

In [18]:
# bunlar değer güncellemez.

In [19]:
# değer güncellemek için: x = x * 3

In [22]:
a = a * 3
a

array([3, 6, 9])