In [1]:
import numpy as np

## Fncy Indexing

In [2]:
# Şimdiye kadar hep belirli elemanları, belirli kesitlerdeki elemanları, veya belirli sayıda elemanları atlaya atlaya elemanları almayı gördük.

In [3]:
# Fancy Indexing ile birkaç tane belirli indexteki elemanı bana döndür diyebilecek olmalıyız.

In [4]:
x = np.arange(1,15)

In [5]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#index alma

In [10]:
idxs = [4, 5, 7, 11] #bu normal bir liste

In [11]:
x[idxs] #bu indexlerdeki elemanları döçndürdü.

array([ 5,  6,  8, 12])

In [12]:
#arrayı yazdık ve indexlerin bulunduğu listeyi verdik.

In [14]:
a = np.arange(12).reshape([3,4])

In [15]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a[0:2,1] # 0. SATIRDAN 2. SATIRA KADAR VE 1. KOLON

array([1, 5])

In [23]:
a[0:2,1].shape # burada tekli olduğundan row column mantığı yok.

(2,)

In [24]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [25]:
a[0:2,1:3].shape

(2, 2)

In [26]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a[0,[1,3]] #bu fancy indexing. Burada olan şey 0. satırı al ve 1. ve 3. sütunu al der.

array([1, 3])

In [32]:
a[0:,[1,3]] #bunun farkı  : konulmasıdır. yani bütün sütunlareı tara diuorum bern ona.

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [33]:
a = np.arange(20).reshape([4,5])

In [34]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
idx1 = [1,3,2]
idx2 = [3,0,2]

In [38]:
a[idx1,idx2] #buradaki mantık 1. 3. 2. row ile 3. 0. ve 2. columnu kesiştir ver

array([ 8, 15, 12])

In [39]:
a[idx1,idx2].shape

(3,)

In [41]:
a[idx1][idx2]  #bu olmaz çünkü neyin ne olduğunu bilmiyotruz.

IndexError: index 3 is out of bounds for axis 0 with size 3

In [42]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
x[[2,6,9]] = 20

In [45]:
x

array([ 1,  2, 20,  4,  5,  6, 20,  8,  9, 20, 11, 12, 13, 14])

In [46]:
x = np.arange(9)

In [47]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
x[[1,2,3]] = [100, 200, 300] 

In [53]:
x

array([  0, 100, 200, 300,   4,   5,   6,   7,   8])