In [1]:
import numpy as np

# Conditional Indexing

In [2]:
a = np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [5]:
# küçükse 5'ten liste oluşturur ve sağlayanlara true girer

In [6]:
a[a<5]

array([1, 2, 3, 4])

In [7]:
filt = a <3

In [8]:
filt

array([ True,  True, False, False, False, False, False, False, False])

In [10]:
a[filt] #hangisini getireceğimizi bu şekilde verebiliyoru.

array([1, 2])

In [11]:
b = np.array([2, 3, 3, 4, 5, 61, 7, 8, 11])

In [12]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [14]:
a == b #aynı şekilde liste oluşturdu.

array([False, False,  True,  True,  True, False,  True,  True, False])

In [16]:
a[a==b] # aynı olanlar ıdöndürdü.

array([3, 4, 5, 7, 8])

In [17]:
b[a==b]

array([3, 4, 5, 7, 8])

In [18]:
# bunları yazmak aynı şey.

In [19]:
# normaldew kurduğumuz or mantığını numpy da kuramıyoruz.

In [20]:
(a < 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
(a < 3) | (a > 5) #bu da or demenin bir yolu.

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [23]:
a[(a < 3) | (a > 5)]

array([1, 2, 6, 7, 8, 9])

In [24]:
filt = (a < 3) | (a > 5)

In [25]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [26]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [29]:
a[(a < 3) & (a > 5)] # bu da ve demek

array([], dtype=int32)

## Filtrenin Değili

In [30]:
#normalde not yazardık 

In [31]:
a = np.arange(1,21).reshape(4,5)

In [33]:
filt =  a < 5

In [34]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [35]:
a[filt]

array([1, 2, 3, 4])

In [36]:
filt = (a > 5) & (a < 9)

In [37]:
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [38]:
# alt + 0126 ya basarsak bu işaret çıkar bunu koymalıyız.

In [39]:
filt = ~((a > 5) & (a < 9))

In [40]:
filt

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [41]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### Multidimensional arraylarda conditional indexing

In [42]:
a = np.arange(1,21).reshape((4,5))

In [43]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [45]:
a[a<7].shape

(6,)

In [46]:
a = np.array([1,2,3,None])

In [47]:
a

array([1, 2, 3, None], dtype=object)

In [48]:
a == None


array([False, False, False,  True])

In [49]:
a

array([1, 2, 3, None], dtype=object)