In [1]:
import numpy as np

# NORMAL DISTRIBUTION'DAN ÇEKILMIŞ DEĞERLER ILE ARRAY OLUŞTUIRMAK

In [2]:
# (mean,std,array size)

In [5]:
np.random.normal(0, 1, (4, 5)) #ortalama, standart sapma, ve en son tuple biçiminde büyüklüğünü yazmalıyız.

array([[ 1.22458071,  0.34264846,  1.05690597, -0.1504092 , -1.20677794],
       [ 0.85528707, -0.09305821, -0.16473055, -0.97776952, -0.29219979],
       [ 0.09284767,  0.69847264,  0.24234678,  0.40784274, -1.17392103],
       [ 0.07224867,  0.51154007, -0.68319898, -0.98147207,  0.8451417 ]])

In [6]:
np.random.normal(0, 100, (4,5))

array([[-132.99373905,   16.4850078 ,  -68.14013082,  192.26045784,
         -97.40564498],
       [ 177.75862253, -173.78470871,  -74.47775224,   67.08581467,
        -313.13672185],
       [ -14.91248323,  159.62607332,   29.64459748,   70.62663297,
         -26.84406488],
       [-151.2532044 ,  -94.88716866,  114.14226411,  -59.62485919,
         -93.81825018]])

In [7]:
np.random.normal(10, 100, (4,5))

array([[  47.23451516,  133.63161245,   33.19014309,  108.15515385,
         105.51690025],
       [ 124.98880155, -148.89352212,  -55.68866355,   43.01414011,
         -71.10102728],
       [-102.31236269,   -1.37293262,   62.62576177, -159.13013071,
        -166.35033754],
       [ 162.35156985,  -30.3283948 ,   -7.19760835,  -13.98187297,
         -77.41328108]])

In [8]:
np.random.normal(10, 1, (4,5))

array([[10.02462431,  9.59058054, 11.74532167,  8.43487104, 10.86846339],
       [10.00604289,  9.52654898,  9.96562111, 10.20055415,  9.92286673],
       [ 9.42751837,  9.84390873,  9.52598086,  9.73012319, 10.43505949],
       [ 9.53927059,  7.93741203,  9.74366836,  9.88286504,  9.90825788]])