In [1]:
import numpy as np

# BELİRTİLEN BİR ELEMANDAN ARRAY OLUŞTURMAK

In [2]:
# np.full ile yapılabilir.

In [3]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [5]:
np.full((4,5),5) # , den sonra yazılan doldurulacak olan

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [6]:
np.full(4,5)

array([5, 5, 5, 5])

In [7]:
np.full((4,5),"a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [8]:
np.full((4,5), 5.2, dtype = "str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [9]:
np.full((4,5), "4,2")

array([['4,2', '4,2', '4,2', '4,2', '4,2'],
       ['4,2', '4,2', '4,2', '4,2', '4,2'],
       ['4,2', '4,2', '4,2', '4,2', '4,2'],
       ['4,2', '4,2', '4,2', '4,2', '4,2']], dtype='<U3')