In [1]:
import numpy as np

# Array Attributeları

In [2]:
# Shape

In [3]:
x = np.zeros((2,3))

In [4]:
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
y = np.zeros((2,5,4))
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
x.shape

(2, 3)

In [9]:
y.shape

(2, 5, 4)

In [10]:
#shaper kaça kaçlık olduğunu bildirir bize.

In [11]:
# Ndim

In [14]:
x.ndim # 2 boyutlu bir row bir colon

2

In [15]:
y.ndim # bu 3 dimentionlu row colon ve sayı

3

In [22]:
# size kaç elemanlı olduğunu döndürür toplam olarak.

In [23]:
x = np.zeros((2,3))
y = np.zeros((2,5,4))

In [24]:
x 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
y 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
x.size

6

In [27]:
y.size

40

In [28]:
# Dtype

In [29]:
x = np.zeros((2,3))

In [30]:
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
x.dtype #data tipini döndürür.

dtype('float64')