In [1]:
import numpy as np

# Sorting

In [2]:
a = np.array([20, 32, 5, 30, 10])

In [3]:
a

array([20, 32,  5, 30, 10])

In [5]:
np.sort(a) #küçüktren büyüğe ve güncellemez

array([ 5, 10, 20, 30, 32])

In [6]:
a

array([20, 32,  5, 30, 10])

In [7]:
a.sort()

In [8]:
a

array([ 5, 10, 20, 30, 32])

### Argsort

In [9]:
a = np.array([3,1,6,5,4,2])

In [10]:
# elemanları aynı şekilde sıralar ve indexzlerini döndürür.

In [12]:
idxs = np.argsort(a)

In [13]:
idxs

array([1, 5, 0, 4, 3, 2], dtype=int64)