In [1]:
import numpy as np

# ALL
* Tüm elemanlar şartı sağlıyor mu ona bakmak.

In [2]:
a = np.arange(1,21).reshape([4,5])

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
a > -1 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
np.all(a>-1) #hepsi şartı sağlıyor mu ona bakıyor.

True

In [8]:
np.all(a>5) #hepsi 5 ten büyük değil.

False

In [9]:
filt = a > -1

In [13]:
a>5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [10]:
np.all(filt)

True

In [11]:
np.all(a>5, axis = 1)

array([False,  True,  True,  True])

In [12]:
np.all(a>5, axis = 0)

array([False, False, False, False, False])

In [14]:
np.all(a>5, axis = 1).ndim

1

In [15]:
np.all(a>5, axis = 0).ndim

1