In [1]:
import numpy as np

# Stack
* Stack mantığını bir dimension ekleyip o dimension üzerinde concatenation yaparak da elde edebiliriz.

#### Stack

In [2]:
a = np.array([1,2,3,4])

In [3]:
b = np.array([5,6,7,8])

In [4]:
a
b

array([5, 6, 7, 8])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a.shape

(4,)

In [7]:
b.shape

(4,)

In [8]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
np.stack([a,b], axis = 0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
np.stack([a,b], axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [13]:
np.stack([a,b], axis = -1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [14]:
# ilginç olan kısım a ve b'nin row veya column'u yok. stack onlara bu değeri katıp istediğimiz şekilde birleştirir.