In [1]:
import numpy as np

# Any
* Herhangi eleman verilen işareti sağlıyor mu kontrol etmek

In [ ]:
# all ile aşağı yukarı aynı şey 

In [2]:
a = np.arange(1,21).reshape([4,5])

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
a > 17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [5]:
np.all(a>17)

False

In [6]:
np.any(a>17)

True

In [9]:
np.any(a>17,axis = 0) # dikeyde

array([False, False,  True,  True,  True])

In [10]:
np.any(a>17,axis = 1) # yatayda

array([False, False, False,  True])