In [1]:
import numpy as np

# RESHAPİNG

* Önemli kısım reshape yapacağımız elemanın yapıldıktan sonraki eleman ile aynı uzunlukta olması yan isizelarının aynı olamsı gerek.

In [2]:
a = np.arange(1,11)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a.ndim

1

In [5]:
a.size

10

In [10]:
a.reshape(2,5) # bunu 2 ye 5 lik şekilde ifade et demek bu 2* 5 = 10 10 elemanlı. Ayrıca bunu yapınca a güncellenmiyor.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
a.reshape(3,5) #bakın olmadı

ValueError: cannot reshape array of size 10 into shape (3,5)

In [12]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
a = a.reshape(2,5) #bunu yaparsak güncelleriz.

In [14]:
a = np.arange(1,11)

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
a.reshape(2,5).ndim # 2 boyutlu oldu artık 2 ye 5 olduğundan.

2

### -1 boyuta karar vermek

In [19]:
a.reshape(-1,2) # aynı size de olmalı bir dimension belli ise öbürünü otomatik atar

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
a.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
a.reshape(-1,6) # toplam 10 eleman olmaz.

ValueError: cannot reshape array of size 10 into shape (6)

## Yeni boyut eklemek.

In [24]:
a = np.arange(1,11)

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
a[np.newaxis, :] # 1 satır yaptı ama bir şey değişmedi çğnkü zaten öyleydi.

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [29]:
a[:,np.newaxis] #bu da ters olanı.

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [30]:
a[:,np.newaxis].shape

(10, 1)

In [31]:
# veya np.newaxis yazmaktansa none yazabiliriz.

In [33]:
a[:,None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])